### ISSUE TITLE
If you mark a checkbox as a required field...

### ISSUE THREAD

**Issue by per4mance** [donmik/buddypress-xprofile-custom-fields-type#15]
on frontend mode you can save the form without checking the box.

Don't know if you knew this? Updated to version 2.1.2 today and this was my experience.

Best Regards,
Thorsten

**Comment by donmik** [comment]
Is this happening with an admin user? When I'm an admin, the checkbox is not required, but it's working for normal users so I guess this is some feature from buddypress allowing admins to uncheck the required field.

**Comment by per4mance** [comment]
Yes, you're right. It happens as admin. Sorry didn't know this. Thanks for your fast reply.

**Comment by donmik** [comment]
You're welcome!
