### ISSUE TITLE
BP_XProfile_Field_Type class not found when bp_enable_multiblog set to true

### ISSUE THREAD

**Issue by dshaw002** [donmik/buddypress-xprofile-custom-fields-type#18]
When I enable bp multiplog in wp-config.php, I get a PHP Fatal Error, Class 'BP_XProfile_FIeld_Type' not found.

**Comment by donmik** [comment]
I have no problem with multisites. Have you changed the name of the folder of buddypress plugin maybe?

**Comment by dshaw002** [comment]
It was a configuration setting. My mistake. Thank you for the response, though.
