### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by JamesSimpson** [donmik/buddypress-xprofile-custom-fields-type#26]
Seems to be a bug in the latest version after I updated:

At line 80 bp-xprofile-custom-fields-type.php, the following require causes a fatal error because Bxcft_Field_Type_Slider.php doesn't exists.
require_once( 'classes/Bxcft_Field_Type_Slider.php' );

Quick fix was to open up bp-xprofile-custom-fields-type.php and comment out:

//require_once( 'classes/Bxcft_Field_Type_Slider.php' );

**Comment by donmik** [comment]
Sorry!
https://github.com/donmik/buddypress-xprofile-custom-fields-type/releases/tag/2.4.1
