### ISSUE TITLE
fatal error on release 2.4.0

### ISSUE THREAD

**Issue by pfhenderson57** [donmik/buddypress-xprofile-custom-fields-type#27]
I just updates to xprofile 2.4.0. I'm immediately getting a fatal error, can't open the plugin.

Warning: require_once(classes/Bxcft_Field_Type_Slider.php): failed to open stream: No such file or directory in /home/wp_3dvuy5/myharbors.com/wp-content/plugins/buddypress-xprofile-custom-fields-type/bp-xprofile-custom-fields-type.php on line 80

Fatal error: require_once(): Failed opening required 'classes/Bxcft_Field_Type_Slider.php' (include_path='.:/usr/local/lib/php:/usr/local/php5/lib/pear') in /home/wp_3dvuy5/myharbors.com/wp-content/plugins/buddypress-xprofile-custom-fields-type/bp-xprofile-custom-fields-type.php on line 80

**Comment by donmik** [comment]
Sorry!

https://github.com/donmik/buddypress-xprofile-custom-fields-type/issues/26
