### ISSUE TITLE
PHP error: Undefined offset (for MultiSelectCustomTaxonomy)

### ISSUE THREAD

**Issue by reubenlillie** [donmik/buddypress-xprofile-custom-fields-type#32]
Undefined offset: 1 in /. . ./wp-content/plugins/buddypress-xprofile-custom-fields-type/classes/Bxcft_Field_Type_MultiSelectCustomTaxonomy.php on line 106

NB, I have two custom taxonomies for the default 'user' post type, one for the default 'page' post type, and several others for standard custom post types. However, since I don't experience the issue with, say, single SelectCustomTaxonomy, I'm not convinced that my code is interfering.

**Comment by donmik** [comment]
Should be solved in 2.6.1
